authenticator/urls.py
import os

from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import (
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.http import HttpResponseRedirect
from django.urls import path

from .forms import SetPasswordForm
from .views import (
    AddNewMemberView,
    AddRole,
    AddUser,
    Authenticate,
    DelRole,
    ImportRole,
    KeycloakSync,
    MigrateUsers,
    PasswordResetView,
    TestAddUser,
    TestDelUser,
    TestSetUserPassword,
    TestUserExists,
    UserInfo,
    heartbeat,
)


def redirect_home(request):
    return HttpResponseRedirect("https://www.crossref.org")


urlpatterns = [
    path("add-new-member/", AddNewMemberView.as_view(), name="add_new_member"),
    path("migrate_users/", MigrateUsers.as_view(), name="migrate_users"),
    path("heartbeat/", heartbeat, name="heartbeat"),
    path("admin/", admin.site.urls),
    path("api/v1/authenticate", Authenticate.as_view(), name="authenticate"),
    path("api/v1/user-info", UserInfo.as_view(), name="userinfo"),
    path("api/v1/add-role/<str:name>", AddRole.as_view(), name="addrole"),
    path("api/v1/add-user", AddUser.as_view(), name="adduser"),
    path("api/v1/del-role/<str:name>", DelRole.as_view(), name="delrole"),
    path("api/v1/import-role", ImportRole.as_view(), name="importrole"),
    path("api/v1/keycloak-sync", KeycloakSync.as_view(), name="keycloaksync"),
    path("reset-password/", PasswordResetView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset-password/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(form_class=SetPasswordForm),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    url("", include("django_prometheus.urls")),
    path("", redirect_home),
]

if "TEST_ADMIN_API" in os.environ:
    urlpatterns.extend(
        [
            path("api/test/adduser", TestAddUser.as_view(), name="testadduser"),
            path(
                "api/test/setuserpwd",
                TestSetUserPassword.as_view(),
                name="testsetuserpwd",
            ),
            path(
                "api/test/userexists/<str:username>",
                TestUserExists.as_view(),
                name="testuserexists",
            ),
            path(
                "api/test/deluser/<str:username>",
                TestDelUser.as_view(),
                name="testdeluser",
            ),
        ]
    )

authenticator/models.py
import os
import uuid

from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from django_keycloak.hashers import PBKDF2SHA512PasswordHasher as keycloak_hasher

from .keycloak_utils import force_keycloak_hash_sync


class KeycloakData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    kc_hash = models.CharField(max_length=200, blank=False)

    def set_password(self, p):
        h = keycloak_hasher()
        self.kc_hash = h.encode(p, salt=str(uuid.uuid4())[-12:])


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):

    # A save event that has nothing to do with password (unless it is creation
    # will be ignored. Same for key users
    if instance.username in ["root", os.environ["AUTH_SVC_USER"]] or (
        not kwargs.get("created", False) and not instance._password
    ):
        return

    try:
        kc = instance.keycloakdata
    except KeycloakData.DoesNotExist:
        kc = KeycloakData.objects.create(user=instance)

    if instance._password:
        kc.set_password(instance._password)
        kc.save()

    # There is no sync for not email users
    try:
        validate_email(instance.username)
    except Exception:
        return

    force_keycloak_hash_sync(instance, kc.kc_hash, kwargs.get("created", False))

authenticator/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm as BasePasswordResetForm
from django.contrib.auth.forms import SetPasswordForm as BaseSetPasswordForm
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

from zxcvbn_password.fields import PasswordConfirmationField, PasswordField


class APIForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class PasswordResetForm(BasePasswordResetForm):
    """
    Overrides Django's PasswordResetForm to no-op its .save() method.

    Django sends the password reset email via this forms .save() method but our
    emails are constructed in a different way.
    """

    def save(self, *args, **kwargs):
        # stop this form from sending out the reset email, it's being handled
        # in the view
        pass


class RequestPasswordResetForm(forms.Form):
    username = UsernameField()
    email = forms.CharField()

    def clean(self):
        """
        Validate form fields

        .clean() is the final step in a Form's validation pipeline and allows
        us to compare multiple fields.

        We use it bail out of validation if a user with the given username
        doesn't exist so the View can handle that.  We also check given email
        address matches the email address of the User derived from the given
        username.
        """
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")

        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            # user with username doesn't exist yet, let the view handle User
            # creation - clean() is just for validation.
            return

        if User.objects.exclude(pk=user.pk).filter(email=email).exists():
            self.add_error("email", "User with this Email already exists.")
            return cleaned_data

        if user.email and user.email != email:
            msg = f"Email address doesn't match the address linked to '{username}': {user.email}"
            self.add_error("email", msg)
            return cleaned_data


class SetPasswordForm(BaseSetPasswordForm):
    """
    Overrides Django's SetPasswordForm to add the password strength fields
    """

    new_password1 = PasswordField(label="New password")
    new_password2 = PasswordConfirmationField(
        confirm_with="new_password1", label="Confirm password"
    )


def new_password():
    return User.objects.make_random_password(length=20)


legacy_role_name_validator = RegexValidator("[a-zA-Z0-9]+")


class AddNewMemberForm(forms.Form):
    legacy_role_name = forms.CharField(
        label="Add role", validators=[legacy_role_name_validator],
    )
    email = forms.EmailField(label="Add email (optional)", required=False,)


class MigrateUsersForm(forms.Form):
    password = forms.CharField(
        label="Keycloak admin password", widget=forms.PasswordInput
    )

authenticator/views.py
import base64
import hashlib
import uuid

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView as BasePasswordResetView
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.views.generic import FormView

import structlog
from keycloak import KeycloakAdmin
from rest_framework.authentication import BasicAuthentication
from rest_framework.parsers import JSONParser
from rest_framework.permissions import IsAdminUser
from rest_framework.views import APIView
from sentry_sdk import capture_exception

from .emails import send_reset_password, send_reset_password_to
from .forms import (
    AddNewMemberForm,
    MigrateUsersForm,
    PasswordResetForm,
    RequestPasswordResetForm,
)
from .keycloak_utils import force_keycloak_hash_sync
from .models import KeycloakData
from .role import Role

logger = structlog.get_logger(__name__)
salt = str(uuid.uuid4())


def heartbeat(request):
    status = "ok"
    status_code = 200

    # This will throw an error and a 500 in the middleware,
    # but make sure we explicitly call it.
    try:
        User.objects.first()
    except Exception:
        status = "fail"
        status_code = 500

    return JsonResponse(
        {"status": status, "r": settings.APP_VERSION_NUMBER}, status=status_code,
    )


class Authenticate(APIView):
    """Authenticate the user supplied in the JSON body and return the roles they have.
    This is protected by Basic Auth, which must bear the credentials of an Admin account."""

    allowed_methods = ["GET", "POST"]
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAdminUser]
    parser_classes = [JSONParser]

    def post(self, request, format=None):

        username = request.data.get("username", "")
        password = request.data.get("password", "")

        try:
            user = User.objects.get(Q(username=username))
        except User.DoesNotExist:
            logger.warn(
                {"action": "authentication", "status": "failed", "user": username}
            )
            return JsonResponse(
                {"status": "failure", "message": "Invalid username or password"},
                status=400,
            )

        if not user.check_password(password):
            pwdmd5 = hashlib.md5()
            pwdmd5.update((salt + password).encode())

            return JsonResponse(
                {"status": "failure", "message": "Invalid username or password"},
                status=400,
            )

        try:
            user.keycloakdata
        except KeycloakData.DoesNotExist:
            kc = KeycloakData.objects.create(user=user)
            kc.set_password(password)
            kc.save()

        role_names = [group.name for group in user.groups.all()]
        logger.info({"action": "authentication", "status": "success", "user": username})
        return JsonResponse(
            {"status": "success", "username": user.username, "legacy_roles": role_names}
        )


class UserInfo(APIView):
    """This view will return extra information about the user"""

    allowed_methods = ["GET", "POST"]
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAdminUser]
    parser_classes = [JSONParser]

    def post(self, request, format=None):

        username = request.data.get("username", "")

        try:
            user = User.objects.get(Q(username=username))
        except User.DoesNotExist:
            return JsonResponse(
                {"status": "failure", "message": "Invalid username or password"},
                status=400,
            )

        role_names = [group.name for group in user.groups.all()]
        return JsonResponse(
            {"status": "success", "username": user.username, "legacy_roles": role_names}
        )


class AddRole(APIView):
    """This view will create a new role"""

    allowed_methods = ["GET"]
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAdminUser]

    def get(self, request, name, format=None):

        try:
            Role.objects.get(Q(name=name))
        except Role.DoesNotExist:
            new_role, created = Role.objects.get_or_create(name=name)
            if not created:
                return JsonResponse(
                    {"status": "failure", "message": "cannot create role"}, status=500,
                )
            else:
                u, created = User.objects.get_or_create(username=name)
                if created:
                    u.set_password(str(uuid.uuid4())[:20])
                    u.groups.add(new_role)
                    u.save()

                return JsonResponse(
                    {"status": "success", "message": "role created"}, status=200,
                )

        return JsonResponse(
            {"status": "success", "message": "role already exists"}, status=200,
        )


class DelRole(APIView):
    """This view will delete a role"""

    allowed_methods = ["GET"]
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAdminUser]

    def get(self, request, name, format=None):

        try:
            role = Role.objects.get(Q(name=name))
        except Role.DoesNotExist:
            return JsonResponse(
                {"status": "success", "message": "role did not exist"}, status=200,
            )

        role.delete()

        return JsonResponse(
            {"status": "success", "message": "role deleted"}, status=200,
        )


class AddUser(APIView):
    """Adds a user into the DB if the user exists it will overwrite the password"""

    allowed_methods = ["POST"]
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAdminUser]
    parser_classes = [JSONParser]

    def post(self, request):
        username = request.data.get("username", None)
        password = request.data.get("password", None)

        if not username or not password:
            return JsonResponse({"status": "failed"}, status=200,)

        user, _ = User.objects.get_or_create(username=username)

        user.set_password(password)
        user.save()

        return JsonResponse({"status": "ok"}, status=200,)


class ImportRole(APIView):
    """Import a role sent by the Content System form.
    Create the Legacy Role and Legacy Credential if it doesn't exist.
    If a password is sent, update the password for the Legacy Role.
    If an email is included, send a reset notification to that email.
    """

    allowed_methods = ["POST"]
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAdminUser]
    parser_classes = [JSONParser]

    def post(self, request):
        legacy_role_name = request.data.get("legacy_role", None)
        address = request.data.get("email", None)
        password = request.data.get("password", None)

        if not legacy_role_name:
            return JsonResponse(
                {"status": "failure", "message": "Legacy Role not provided"},
                status=400,
            )

        if address and password:
            return JsonResponse(
                {
                    "status": "failure",
                    "message": "Supply only email or password, not both.",
                },
                status=400,
            )

        # Create both a Legacy Role (Role) and Legacy Credential (User).
        legacy_role, legacy_role_created = Role.objects.get_or_create(
            name=legacy_role_name
        )

        legacy_credential, legacy_credential_created = User.objects.get_or_create(
            username=legacy_role_name
        )

        # When new always set a password, either supplied or unusable.
        if legacy_credential_created:
            if password:
                legacy_credential.set_password(password)
            else:
                legacy_credential.set_unusable_password()
        else:
            # If not new and password supplied, update it.
            if password:
                legacy_credential.set_password(password)

        # First time associate user (credential) with group (role).
        if legacy_credential_created:
            legacy_credential.groups.add(legacy_role)

        legacy_credential.save()

        if address:
            # Email is exclusively for sending a reset message. It isn't associated
            # with the user beyond that and isn't stored.
            send_reset_password_to(self.request, legacy_credential, address)

        return JsonResponse({"status": "ok"}, status=200,)


class KeycloakSync(APIView):
    """If a user is created in Keycloak via Keymaker, Keymaker will use this
    endpoint to send the user created. If:
    - The user exists in authenticator: the hash will be send to keycloak for synchronization
    - The user DOES NOT exist in authenticator: it will be created in authenticator and a
      email for password setup will be sent, no role will be assigned
    """

    allowed_methods = ["POST"]
    authentication_classes = [BasicAuthentication]
    permission_classes = [IsAdminUser]
    parser_classes = [JSONParser]

    def post(self, request):
        username = request.data.get("username", None)

        if not username:
            return JsonResponse(
                {"status": "failure", "message": "username not provided"}, status=400,
            )

        try:
            validate_email(username)
        except ValidationError:
            return JsonResponse(
                {
                    "status": "failure",
                    "message": "username must be a valid email address",
                },
                status=400,
            )

        status = "OK"
        code = 200

        try:
            user = User.objects.get(Q(username=username))

authenticator/templates/add_new_member.html
{% extends "base.html" %}

{% block content %}

<h2>Add new member</h2>



<section>
<div>
<a class="authentication-button" href="/admin"> Back</a>
</div>          
</section>

</br>

<!-- <div class="banner">
  <p>This is a temporary method to add new members, as we progress to migrate all of our members to email credentials and role based login.</p>
</div> -->

<h3>Create User Credentials</h3>
<p>To create user credentials, enter the role and email address. If this user is not in the system, they will receive an email to set a password. If they are already in the system, they will be associated with the role and can log in using their existing password.</p>

<!--- <hr style="height:1px;border-width:0;color:gray;background-color:#DADADA">

<p class="small">• Create legacy role with the given name [Only during test phase].<br>• Create legacy credential user with the same username as Legacy role name and a random hidden password. [This Legacy ‘user’ type is so we can trigger manual password resets for Legacy passwords]<br>• If an email address is supplied, and the User is not known, an email will be sent to the User to create a new password, which will trigger the create password flow.<br></p> --->

<br>
<!------ FORM ------>
<form class="authentication-form" method="post">{% csrf_token %}
	
  {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
		<p>{{ field.label_tag }}</p>
		<p>{{ field }}</p>
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
	<br>
	

	
	<input type="submit" value="Add new">
</form>
<!------ FORM ------>
{% endblock %}

authenticator/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<!-- Header --->
	<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Crossref Authenticator</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    {% block extra_head %}{% endblock %}
  </head>
<!-- Header --->

<!-- Body --->
  <body>
    <div class="header">
      <div class="header-content">
        <img src="https://assets.crossref.org/logo/crossref-logo-landscape-200.svg" alt="Crossref logo">
      </div>
    </div>

    <div class="content">
        <div id="environment-banner"></div>
      {% block content %}{% endblock %}
    </div>


    <script type="application/javascript" src="{% static 'js/get-environment.umd.min.js' %}"></script>
  </body>
<!-- Body --->

</html>

authenticator/templates/migrate_users.html
{% extends "base.html" %}

{% block content %}

<h2>Migrate users to keycloak</h2>



<section>
<div>
<a class="authentication-button" href="/admin"> Back</a>
</div>          
</section>

</br>


<h3>Keycloak credentials</h3>
<p>This process will migrate users that have 512bit password into keycloak. In the following table you can see how many users are ready to be moved:</p>

<table border=1>
  <th>
    <td> Total users </td>
    <td> Compatible users </td>
    <td> Incompatible users </td>
  </th>
  <tr>
    <td> # </td>
    <td> {{ compatible_users|add:non_compatible_users }} </td>
    <td> {{ compatible_users }} </td>
    <td> {{ non_compatible_users }} </td>
  </tr>
</table>

<p>The password for the user admin on Keycloak will be needed to start the migration.</p>

<br>
{% if keycloak_server %}
<!------ FORM ------>

<code><b>KEYCLOAK_SERVER: </b>{{ keycloak_server  }}</code>

<form class="authentication-form" method="post">{% csrf_token %}
	
  {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
		<p>{{ field.label_tag }}</p>
		<p>{{ field }}</p>
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
	<br>
	

	
	<input type="submit" value="Start migration">
</form>
<!------ FORM ------>
{% else %}

<p>You cannot run this migration if you have not set up a keycloak server URL in the settings variable <b>KEYCLOAK_SERVER</b></p>

{% endif %}
{% endblock %}

authenticator/templates/request_password_reset.html
{% extends "admin/base_site.html" %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
{% endblock %}

{% block title %}Reset password{{ block.super }}{% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}

  <fieldset class="aligned">
    <div class="form-row field-username{% if form.errors %} errros{% endif %}">
      <label class="required" for="id_username">Username:</label>
      <input type="text" name="username" autofocus required id="id_username" value="{{ form.username.value|default:"" }}" />
      <ul class="errorlist">
        {% for error in form.username.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </div>

    <div class="form-row field-email{% if form.errors %} errors{% endif %}">
      <label class="required" for="id_email">Email:</label>
      <input type="text" name="email" autofocus required id="id_email" value="{{ form.email.value|default:"" }}" />
      <ul class="errorlist">
        {% for error in form.email.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </div>

    <input type="submit" value="Reset" name="_saveasnew" />

  </fieldset>

</form>
{% endblock content %}